[package]
name = "covid"
version = "0.1.0"
authors = ["freemanbach <flo@radford.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.0"
tqdm-rs = "0.1.0"
prgrs   = "0.6.4"
